[tool.poetry]
name = "your_project_name"
version = "0.1.0"
description = "Your project description"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.24.1"

[build-system]
requires = ["poetry>=1.5.1"]
build-backend = "poetry.core.masonry.api"
